mqtt:
  host: XXX.XXX.XXX.XXX
  port: 1883
  username: homeassistant
  password: your_mqtt_password
  topic_prefix: home/camera

cameras:
  front:
    type: thingino
    manufacturer: Sonoff
    model: PT2
    host: XXX.XXX.XXX.XXX
    port: 80
    username: thingino_username
    password: thingino_password
    device_id: 59ed0c90be0f836074675f3fb7156450
