services:
  ptz-camera-bridge:
    container_name: ptz-camera-bridge

    build: .

    restart: unless-stopped

    volumes:
      - ./config.yaml:/app/config.yaml:ro

    environment:
      - TZ=Europe/Vienna

    networks:
      - camera-net


networks:
  camera-net:
    external: true
