services:
  ptz-camera-bridge:
    container_name: ptz-camera-bridge

    build: .

    restart: unless-stopped

    volumes:
      - ./src:/app
      - ./config.yaml:/app/config.yaml:ro

    environment:
      - TZ=Europe/Budapest
