services:
  ptz-bridge:
    container_name: ptz-bridge
    image: ptz-bridge:latest
    restart: unless-stopped

    networks:
      - camera-net

    volumes:
      - ./config.yaml:/app/config.yaml:ro

    environment:
      - TZ=Europe/Vienna


networks:
  camera-net:
    external: true
